version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=nft_auctions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./fill_db.sql:/docker-entrypoint-initdb.d/fill_data.sql
